manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Ayo-view/', admin.site.urls),

    path('', include('manager_webapp.urls')),
]

manager_webapp/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.home, name="home"),

    path('register', views.register, name="register"),
    
    path('login', views.login, name="login"),

    path('logout', views.logout, name="logout"),

    path('dashboard', views.dashboard, name="dashboard"),

    path('admin-dashboard', views.adminDashboard, name="admin-dashboard"),

    path('admin-updates/<int:pk>', views.adminUpdateRequest, name='admin-updates'),

    path('create-record', views.createRecord, name="create-record"),

    path('update-record/<int:pk>/', views.updateRecord, name="update-record"),
    
    path('request/<int:pk>', views.viewRecord, name="view-request"),

    path('delete-record/<int:pk>', views.deleteRecord, name="delete-record"),
]

manager_webapp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings 

# Email validation, make sure that only emails ending with @arm are valid
email_validator = RegexValidator(
    regex=r'^[a-zA-Z0-9_.+-]+@arm\.com$',
    message="Email must be a valid email address ending with @arm.com.",
)

class Employee(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fullName = models.CharField(max_length=255, verbose_name="Full Name")
    workEmail = models.CharField(max_length=255, verbose_name="Work Email", validators=[email_validator])
    lineManager = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='line_managed')

    def __str__(self):
        return self.fullName

class Request(models.Model):
    REQUEST_TYPES = [
        ('DeviceRequest', 'Device Request'),
        ('MaintenanceRequest', 'Maintenance Request'),
        ('OtherRequest', 'Other'),
    ]

    dateCreated = models.DateTimeField(auto_now_add=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, related_name='requests')
    request = models.CharField(max_length=550)
    request_type = models.CharField(max_length=20, choices=REQUEST_TYPES, verbose_name="Request Type")

    def __str__(self):
        return f"{self.id} - {self.employee.fullName}'s request"

class RequestUpdate(models.Model):
    request = models.ForeignKey(Request, on_delete=models.CASCADE, related_name='updates')
    update_date = models.DateTimeField(auto_now_add=True)
    update_text = models.TextField()

    def __str__(self):
        return f"Update for Request ID {self.request.id} on {self.update_date}"

manager_webapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

from .models import Request, Employee, RequestUpdate

#create a user

class CreateUserForm(UserCreationForm):
    fullName = forms.CharField(required=True)
    workEmail = forms.EmailField(required=True)
    lineManager = forms.ModelChoiceField(queryset=Employee.objects.all(), required=False, empty_label="Select Line Manager (if any)")

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'fullName', 'workEmail', 'lineManager']

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['lineManager'].queryset = Employee.objects.all()

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            # Create the employee profile
            employee = Employee.objects.create(
                user=user,
                fullName=self.cleaned_data['fullName'],
                workEmail=self.cleaned_data['workEmail'],
                lineManager=self.cleaned_data.get('lineManager')  # Get the lineManager if provided
            )
        return user
    

#login a user

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

class CreateRequest(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['request', 'request_type']
        

class UpdateRequest(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['request', 'request_type']

class RequestUpdateForm(forms.ModelForm):
    class Meta:
        model = RequestUpdate
        fields = ['update_text']

manager_webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateUserForm, LoginForm, CreateRequest, UpdateRequest, RequestUpdateForm
from django.contrib.auth.models import auth
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from .models import Request, Employee, RequestUpdate
from django.contrib import messages

# create view here. Will need views for homepage, dashboard, login, various forms etc

def home(request):

    return render(request, "manager_webapp/index.html")

def register(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "You're registered!")
            return redirect("login")
    else:
        form = CreateUserForm()
    
    context = {'form': form}
    return render(request, "manager_webapp/register.html", context=context)

def login(request):
    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                # Check if the user is an admin
                if user.is_staff:
                    return redirect("admin-dashboard")  # Redirect to the admin dashboard
                else:
                    return redirect("dashboard")  # Redirect to the general dashboard

    context = {'form': form}
    return render(request, "manager_webapp/login.html", context=context)

@login_required(login_url='login')
def dashboard(request):
    # Ensure that we only get requests related to the logged-in user's employee profile
    try:
        employee = request.user.employee
        requests = Request.objects.filter(employee=employee)
    except Employee.DoesNotExist:
        requests = []

    context = {'requests': requests}
    return render(request, "manager_webapp/dashboard.html", context=context)

@staff_member_required
def adminDashboard(request):
    all_requests = Request.objects.all().order_by('-dateCreated')
    context = {'all_requests': all_requests}
    return render(request, "manager_webapp/admin-dashboard.html", context=context)

@staff_member_required
def adminUpdateRequest(request, pk):
    requestID = get_object_or_404(Request, pk=pk)
    if request.method == 'POST':
        form = RequestUpdateForm(request.POST)
        if form.is_valid():
            update = form.save(commit=False)
            update.request = requestID
            update.save()
            messages.success(request, "Request update sent")
            return redirect("admin-dashboard")
    else:
        form = RequestUpdateForm()
    
    context = {'form': form, 'request': requestID}
    return render(request, "manager_webapp/admin-updates.html", context=context)

@login_required(login_url='login')
def createRecord(request):
    if request.method == "POST":
        form = CreateRequest(request.POST)
        if form.is_valid():
            # Save the form but don't commit to DB yet, so we can add the employee
            request_instance = form.save(commit=False)
            # Assuming the current user is the one making the request
            # Ensure there's an Employee instance related to the user
            try:
                employee = request.user.employee
                request_instance.employee = employee
                request_instance.save()
                messages.success(request, "Record created successfully.")
                return redirect("dashboard")
            except Employee.DoesNotExist:
                form.add_error(None, "Employee profile not found for the user.")
    else:
        form = CreateRequest()

    context = {'form': form}
    return render(request, "manager_webapp/create-record.html", context=context)

@login_required(login_url='login')
def updateRecord(request, pk):
    requestId = Request.objects.get(id=pk)
    form = UpdateRequest(instance=requestId)
    if request.method == "POST":
        form = UpdateRequest(request.POST, instance=requestId)
        if form.is_valid():
            form.save()
            messages.success(request, "Request updated successfully.")
            return redirect("dashboard")
    context = {'form': form}
    return render(request, "manager_webapp/update-record.html", context=context)

@login_required(login_url='login')
def viewRecord(request, pk):
    requestId = Request.objects.get(id=pk)
    isAdmin = request.user.is_staff
    context = {'request': requestId, 'isAdmin': isAdmin}
    return render(request, "manager_webapp/view-record.html", context=context)

@login_required(login_url='login')
def deleteRecord(request, pk):
    requestId = Request.objects.get(id=pk)

    if request.method == "POST":
        requestId.delete()
        messages.success(request, "Request deleted successfully.")
        return redirect("dashboard")
    else:
        return render(request, "manager_webapp/confirm-delete.html", {'request': requestId})

def logout(request):
    auth.logout(request)
    messages.success(request, "See you soon!")
    return redirect("login")

manager_webapp/templates/manager_webapp/admin-dashboard.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
<h2>All Requests</h2>
<ul>
    {% for req in all_requests %}
    <li>
        Request ID: {{ req.id }} | Requested by: {{ req.employee.user.username }}
        - <a href="{% url 'view-request' req.id %}">View Request</a> | 
        <a href="{% url 'admin-updates' req.id %}">Add Request Update</a> |
   </li>
    {% endfor %}
</ul>
{% endblock %}

manager_webapp/templates/manager_webapp/admin-updates.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
<h2>Update Request</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Update</button>
</form>
{% endblock %}

manager_webapp/templates/manager_webapp/base.html
{% load static %}

<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- used to ensure responsiveness on mobile devices -->
        <title> Log-it </title>
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/minty/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        <!-- Navbar -->
        {% include 'manager_webapp/navbar.html' %}
        
        <div class="container">
            <br>
            <!-- Notifications -->
            {% if messages %}
                <div class="mt-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <!-- Main Content -->
            {% block content %}
            {% endblock %}
        </div>

        <script src="{% static 'js/app.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>

</html>

manager_webapp/templates/manager_webapp/confirm-delete.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Confirm Delete</h2>
    <p>Are you sure you want to delete this request?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'dashboard' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

manager_webapp/templates/manager_webapp/create-record.html
{% extends 'manager_webapp/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

    <body>
        <div class="container bg-light shadow-md p-4 form-layout">
            <h3> Create Request </h3>
        
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
        
                <br>
        
                <button type="submit" class="btn btn-primary w-100 btn-block p-2">
                    Create Request 
                </button>
            </form>
        
        </div>
    </body>


{% endblock %}

manager_webapp/templates/manager_webapp/dashboard.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
    <h1>Dashboard for {{ request.user.username }}</h1>

    <hr>
    <a class="btn btn-primary" type="button" href="{% url 'create-record' %}">Create a Request</a>
    <hr>

    <table class="table table-hover table-bordered">
        <thead class="table-light">
            <tr>
                <th scope="col">Date Created</th>
                <th scope="col">Request</th>
                <th scope="col">Request Type</th>
                <th scope="col">View</th>
            </tr>
        </thead>
        <tbody>
            {% if requests %}
                {% for request in requests %}
                <tr>
                    <td>{{ request.dateCreated|date:"Y-m-d H:i" }}</td>
                    <td>{{ request.request }}</td>
                    <td>{{ request.get_request_type_display }}</td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{% url 'view-request' request.id %}">
                            View
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">No requests found</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
{% endblock %}

manager_webapp/templates/manager_webapp/index.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
    <body>
        <!-- content of sitte here once planned...-->

        <div class="text-center">
            {% if user.is_staff %}
                <h2> Log-it Admin page</h2>
            {% else %}
                <h2> Log-it</h2>
            {% endif %}
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <a class="btn btn-secondary" type="button" href="{% url 'admin-dashboard' %}"> View Dashboard</a>
                {% else %}
                <a class="btn btn-secondary" type="button" href="{% url 'dashboard' %}"> View Dashboard</a>
                {% endif %}
            {% else %}
                <a class="btn btn-primary" type="button" href="{% url 'register' %}"> Create Account</a>
                <a class="btn btn-secondary" type="button" href="{% url 'login' %}"> Sign In</a>
            {% endif %}
        </div>
    </body>
{% endblock %}

manager_webapp/templates/manager_webapp/login.html
{% extends 'manager_webapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <body>
        <div class="container bg-light shadow-md p-4 form-layout">
            <h3> Login </h3>
        
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
        
                <br>
        
                <button type="submit" class="btn btn-primary w-100 btn-block p-2"> Sign in </button>
            </form>
            <br>
        
            <div class="text-center">
                <p> I don't have an account </p> <a href="{% url 'register' %}"> Sign up </a>
            </div>
        
        </div>
        <br>
    </body>

{% endblock %}

manager_webapp/templates/manager_webapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center">
  {% if not request.path == '/' %}
    <a class="navbar-brand main-heading" href="{% url 'home' %}">  <!-- Ensure this points to your home page view name -->
      &nbsp; Log-it
    </a>

    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        &nbsp; &nbsp; &nbsp;
        {% if user.is_authenticated %}
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin-dashboard' %}">Admin Dashboard &nbsp; <i class="fa fa-home" aria-hidden="true"></i></a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard &nbsp; <i class="fa fa-home" aria-hidden="true"></i></a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Sign out &nbsp; <i class="fa fa-sign-out" aria-hidden="true"></i> </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}"> Sign Up </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Sign In</a>
          </li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
</nav>

manager_webapp/templates/manager_webapp/register.html
{% extends 'manager_webapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <body>
        <div class="container bg-light shadow-md p-4 form-layout">
            <h3> Create Account </h3>
        
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
        
                <br>
        
                <button type="submit" class="btn btn-primary w-100 btn-block p-2"> Create </button>
            </form>
            <br>
        
            <div class="text-center">
                <p> I have an account </p> <a href="{% url 'login'%}"> Login </a>
            </div>
        
        </div>
        <br>
    </body>
{% endblock %}

manager_webapp/templates/manager_webapp/update-record.html
{% extends 'manager_webapp/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

    <body>
        <div class="container bg-light shadow-md p-4 form-layout">
            <h3> Update Request </h3>
        
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
        
                <br>
        
                <button type="submit" class="btn btn-primary w-100 btn-block p-2">
                    Update Request 
                </button>
            </form>
        
        </div>
    </body>


{% endblock %}

manager_webapp/templates/manager_webapp/view-record.html
{% extends 'manager_webapp/base.html' %}

{% block content %}
<div class="card bg-light mb-3" style="max-width: 40rem;">
    <div class="card-header">
        <strong>{{ request.get_request_type_display }}</strong>
        <strong>{{ request.employee.fullName }}</strong>
    </div>
    <div class="card-body">
        <p><strong>ID:</strong> {{ request.id }}</p>
        <p><strong>Work Email:</strong> {{ request.employee.workEmail }}</p>
        <p>
            <strong>Line Manager:</strong> 
            {% if request.employee.lineManager %}
                {{ request.employee.lineManager.fullName }}
            {% else %}
                N/A
            {% endif %}
        </p>
        <p><strong>Request:</strong> {{ request.request }}</p>
        <p><strong>Date Created:</strong> {{ request.dateCreated }}</p>
        {% for update in request.updates.all %}
            <div>
                <strong>Update on {{ update.update_date }}:</strong> {{ update.update_text }}
            </div>
        {% endfor %}
    </div>

    {% if not isAdmin %}
        <a href="{% url 'update-record' request.id %}" class="btn btn-primary">Edit Request</a>
        <a href="{% url 'delete-record' request.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this request?');">Delete Request</a>
    {% else %}
    <a href="{% url 'admin-updates' request.id %}" class="btn btn-secondary">Add Request Update</a>
    {% endif %}
    
    <a href="{% if isAdmin %}{% url 'admin-dashboard' %}{% else %}{% url 'dashboard' %}{% endif %}" class="btn btn-primary">Return to Dashboard</a>
</div>
{% endblock %}